### ISSUE TITLE
Generate sigs that start with the current instruction?

### ISSUE THREAD

**Issue by xchgrbprsp** [ajkhoury/SigMaker-x64#17]
Is there a way to only generate sigs that start with the current instruction? I find sigs to the containing function sometimes unreliable or even useless.

**Comment by gir489** [comment]
Can you give an example? Not sure what you're asking.

**Comment by xchgrbprsp** [comment]
For example, sometimes it generates sigs like this but this is not what I wanted.
![func](https://user-images.githubusercontent.com/5180851/45214120-26461600-b2cc-11e8-96eb-e7ae5d71fa9f.jpg)

Sometimes it generates sigs to the previous instruction.
![direct](https://user-images.githubusercontent.com/5180851/45214125-2a723380-b2cc-11e8-95e7-143da5c181d7.jpg)

Previous versions (versions that work with IDA 6.8) only seem to generate sigs that start with the current instruction and oftentimes this is very useful.

**Comment by gir489** [comment]
IDK, this sounds like something I'd rather not do since this is a design issue, rather than an actual implementation issue. @dude719 Do you want to take this? I certainly don't.

**Comment by dude719** [comment]
If you 100% want a sig at the target instruction then generate a sig by highlighting starting from the target instruction, and then select "Create ida pattern from selection". 

The reason that you sometimes will not get any results starting at the target instruction is because there is not a signature unique enough around that area for it to return any results. Therefore your solution should be to manually highlight the target instruction and generate a sig from that selection. 

I can add an option to the configuration panel of the plugin to make sure it filters out any results that dont begin with the target instruction, however, that is defeating the purpose of the plugin, which is to find **unique** signatures.

**Comment by Randshot** [comment]
@dude719 Maybe add an option for prioritizing direct signatures for the target instruction?
At the moment there are only options for signature length and amount of wildcards (if I remember right).

**Comment by gir489** [comment]
@dude719 I vote no on adding a configuration entity for this. This is just enabling bad behaviour and practice. I think we need to either enforce consistent behaviour or remove auto generate entirely. This is purely a case of telling people what they need, and they need to follow proper procedure.

**Comment by xchgrbprsp** [comment]
The problem I'm having is that sometimes ida will fail to identify the containing function because the code is obfuscated in a way that uses all sorts of jmp instructions to break functions apart and mix with other functions.
If you check my example above, the function is certainly not 0x1c7a bytes long. It's just that ida doesn't know where the function starts and ends. So in this case the signature generated is quite useless.

**Comment by xchgrbprsp** [comment]
So I did use "Create ida pattern from selection" in that case but the problem with that is I don't know how many instructions I need to select to generate the shortest unique pattern. That's why I would much appreciate an option that specify what type of signatures to generate so I can still use the auto generate.
